# -*- mode: ruby -*-
# vi: set ft=ruby :

iprange = "192.168.1"
domain = "shibusa.io"

Vagrant.require_version ">= 1.9.7"
Vagrant.configure("2") do |config|
  # Vagrant ssh private key
  config.ssh.private_key_path = ["~/.ssh/id_rsa", "~/.vagrant.d/insecure_private_key"]
  config.ssh.insert_key = false

  # DNS Primary, Puppet Master, Docker Registry
  config.vm.define "corenode-0" do |node|
    node.vm.provider :virtualbox do |vb|
      vb.memory = 2048
      vb.cpus = 2
    end
    node.vm.box = "centos/7"
    node.vm.hostname = "corenode-0.#{domain}"
    node.vm.network "public_network", bridge: "en0: Wi-Fi (AirPort)", ip: "#{iprange}.10"
    node.vm.provision "file", source: "~/.ssh/id_rsa", destination: "~/.ssh/id_rsa"
    node.vm.provision "file", source: "~/.ssh/id_rsa.pub", destination: "~/.ssh/authorized_keys"
    node.vm.provision "file", source: "./vagrantdata/VBoxGuestAdditions_5.1.26.iso", destination: "/tmp/VBoxGuestAdditions_5.1.26.iso"
    node.vm.provision "file", source: "./vagrantdata/puppet-enterprise-2017.2.3-el-7-x86_64.tar.gz", destination: "/tmp/puppet-enterprise-2017.2.3-el-7-x86_64.tar.gz"
    node.vm.provision :shell, path: "./vagrantdata/init.sh"
    node.vm.provision :shell, path: "./vagrantdata/vboxguest.sh"
    node.vm.provision :shell, path: "./vagrantdata/bindmaster.sh"
    node.vm.provision :shell, path: "./vagrantdata/puppetmaster.sh"
    node.vm.provision :shell, path: "./vagrantdata/dockermodule.sh"
    # node.vm.provision :shell, inline: "docker run -d -p 5000:5000 --restart=always --name registry registry:2"
  end

  # DNS Secondary
  config.vm.define "corenode-1" do |node|
    node.vm.box = "centos/7"
    node.vm.hostname = "corenode-1.#{domain}"
    node.vm.network "public_network", bridge: "en0: Wi-Fi (AirPort)", ip: "#{iprange}.11"
    node.vm.provision "file", source: "~/.ssh/id_rsa", destination: "~/.ssh/id_rsa"
    node.vm.provision "file", source: "~/.ssh/id_rsa.pub", destination: "~/.ssh/authorized_keys"
    node.vm.provision "file", source: "./vagrantdata/VBoxGuestAdditions_5.1.26.iso", destination: "/tmp/VBoxGuestAdditions_5.1.26.iso"
    node.vm.provision "file", source: "./vagrantdata/puppet-enterprise-2017.2.3-el-7-x86_64.tar.gz", destination: "/tmp/puppet-enterprise-2017.2.3-el-7-x86_64.tar.gz"
    node.vm.provision :shell, path: "./vagrantdata/init.sh"
    node.vm.provision :shell, path: "./vagrantdata/vboxguest.sh"
    node.vm.provision :shell, path: "./vagrantdata/bindslave.sh"
    node.vm.provision :shell, path: "./vagrantdata/puppetagent.sh"
    # node.vm.provision :shell, inline: "docker run -d -p 5000:5000 --restart=always --name registry registry:2"
  end

  # Docker Manager Nodes
  managercount = 3
  manageripstart = 20
  (0..managercount - 1).each do |i|
    config.vm.define "managernode-#{i}" do |node|
      node.vm.box = "centos/7"
      node.vm.hostname = "managernode-#{i}.#{domain}"
      node.vm.network "public_network", bridge: "en0: Wi-Fi (AirPort)", ip: "#{iprange}.#{manageripstart + i}"
      node.vm.provision "file", source: "~/.ssh/id_rsa", destination: "~/.ssh/id_rsa"
      node.vm.provision "file", source: "~/.ssh/id_rsa.pub", destination: "~/.ssh/authorized_keys"
      node.vm.provision "file", source: "./vagrantdata/VBoxGuestAdditions_5.1.26.iso", destination: "/tmp/VBoxGuestAdditions_5.1.26.iso"
      node.vm.provision :shell, path: "./vagrantdata/init.sh"
      node.vm.provision :shell, path: "./vagrantdata/vboxguest.sh"
      node.vm.provision :shell, path: "./vagrantdata/dnsadd.sh"
      node.vm.provision :shell, path: "./vagrantdata/puppetagent.sh"
    end
  end

  # # Docker Worker Nodes
  # workercount = 3
  # workeripstart = 30
  # (0..workercount - 1).each do |i|
  #   config.vm.define "workernode-#{i}" do |node|
  #     node.vm.box = "centos/7"
  #     node.vm.hostname = "workernode-#{i}.#{domain}"
  #     node.vm.network "public_network", bridge: "en0: Wi-Fi (AirPort)", ip: "#{iprange}.#{workeripstart + i}"
  #     node.vm.provision "file", source: "~/.ssh/id_rsa", destination: "~/.ssh/id_rsa"
  #     node.vm.provision "file", source: "~/.ssh/id_rsa.pub", destination: "~/.ssh/authorized_keys"
  #     node.vm.provision "file", source: "./vagrantdata/VBoxGuestAdditions_5.1.26.iso", destination: "/tmp/VBoxGuestAdditions_5.1.26.iso"
  #     node.vm.provision :shell, path: "./vagrantdata/init.sh"
  #     node.vm.provision :shell, path: "./vagrantdata/vboxguest.sh"
  #     node.vm.provision :shell, path: "./vagrantdata/dnsadd.sh"
  #     node.vm.provision :shell, path: "./vagrantdata/puppetagent.sh"
  #   end
  # end
end
